<?php

// Auto generated by wpfluent Installer.

return array(
    'name'         => 'Fluent Booking Pro',
    'slug'         => 'fluent-booking-pro',
    'domain_path'  => '/language',
    'text_domain'  => 'fluent-booking-pro',
    'hook_prefix'  => 'fluent-booking-pro',
    'rest_version' => 'v2',
    'env'          => 'dev'
);
